# This file can be used for testing the API with a dedicated Visual Studio Code extension.

## Get all avaiable services.
GET http://localhost:3001/api/services HTTP/1.1
###

## Get new ticket.
POST http://localhost:3001/api/newTicket HTTP/1.1
content-type: application/json

{
    "serviceName": "Money Order"
}
###

## Get all counters.
GET http://localhost:3001/api/counters
###

### Test case for calling the next customer at a specific counter
POST http://localhost:3001/api/callNextCustomer
Content-Type: application/json

{
    "counterId": "4"
}

### Add a new service
POST http://localhost:3001/api/addService
Content-Type: application/json

{
    "name": "Money Order",
    "serviceTime": 20
}

### List all services
GET http://localhost:3001/api/services


### Getting Customers for Each Counter
GET http://localhost:3001/api/getCustomersForEachCounter
Accept: application/json


### Get customers for each counter by service type
GET http://localhost:3001/api/getCustomersForEachCounterByService
Accept: application/json

### Daily Stats
GET http://localhost:3001/api/getOverallStats?period=daily
Accept: application/json

### Weekly Stats
GET http://localhost:3001/api/getOverallStats?period=weekly
Accept: application/json

### Get the number of customers served for each service type by day
GET http://localhost:3001/api/statistics/customersForServiceOnDay/2024-10-15

### Get the number of customers served for each service type by week
GET http://localhost:3001/api/statistics/customersForServiceOnWeek/42/2024

### Get the number of customers served for each service type by month
GET http://localhost:3001/api/statistics/customersForServiceOnMonth/10/2024



 