# This file can be used for testing the API with a dedicated Visual Studio Code extension.

## Get all avaiable services.
GET http://localhost:3000/api/services HTTP/1.1
###

## Get new ticket.
POST http://localhost:3000/api/newTicket HTTP/1.1
content-type: application/json

{
    "serviceName": "shipping"
}
###

### Test case for calling the next customer at a specific counter
POST http://localhost:3001/api/callNextCustomer
Content-Type: application/json

{
    "counterId": "1"
}

 

 

 